-- SQL Analysis phase - PART1(Basic Queries)
USE amazon_ecommerce;

-- 1. What is the total revenue generated by the company?
SELECT SUM(total_sales_inr) AS 'Total_revenue' FROM orders;

-- 2. How many total orders were placed?
SELECT COUNT(*) AS 'TOTAL_ORDERS' FROM orders;

-- 3. How many unique customers made purchases?
SELECT COUNT(*) AS Total_Customers FROM customers;

-- 4. How many unique products are available?
SELECT COUNT(product_id) AS Total_Products FROM products;
-- 5. What is the average order value?
SELECT ROUND(AVG(total_sales_inr),2) AS Avg_Order_Value FROM orders;

-- 6. What is the highest order value?
SELECT MAX(total_sales_inr) AS Highest_Order FROM orders;

-- 7. What is the lowest order value?
SELECT MIN(total_sales_inr) AS Lowest_Order FROM orders;

-- 8. How much revenue was generated by each product category?
SELECT p.product_category,
    ROUND(SUM(o.total_sales_inr),2) AS 'Revenue'
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.product_category
ORDER BY Revenue DESC;

-- 9. Which payment method was used the most?
SELECT payment_method,count(*) AS 'total_orders' FROM orders
group by payment_method;

-- 10. How many orders are in each delivery status?
SELECT delivery_status, COUNT(*) AS 'Total_order'
FROM orders
GROUP BY delivery_status;

-- 11. What is the average customer rating for each product category?
SELECT p.product_category,AVG(review_rating) AS 'avg_rating' FROM orders o
JOIN products p
ON o.product_id=p.product_id
GROUP BY p.product_category
ORDER BY avg_rating DESC;

-- 12. Which are the top 10 highest revenue-generating products?
SELECT t2.product_name, SUM(t1.total_sales_inr) AS 'Revenue' FROM orders t1
JOIN products t2
ON t1.product_id=t2.product_id
GROUP BY t2.product_name
ORDER BY Revenue DESC
LIMIT 10;

